export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_BOOTCAMPS = "GET_BOOTCAMPS";
export const BOOTCAMP_ERROR = "BOOTCAMP_ERROR";
